# Generated by Django 4.2.7 on 2023-11-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.FileField(blank=True, default='https://cdn.bulldogjob.com/system/companies/logos/000/001/041/thumb/bulldogjob_avatar_01.png', null=True, upload_to=''),
        ),
    ]
