# Generated by Django 4.2.7 on 2023-11-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.FileField(blank=True, default='itransition_logo.png', null=True, upload_to=''),
        ),
    ]
